kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: decisionapp
  namespace: cp4na
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - pods