kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: decisionapp
  namespace: cp4na
subjects:
  - kind: ServiceAccount
    name: decisionapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: decisionapp